import 'forwarders/effect_forwarder_test.dart' as effect_forwarder_test;
import 'systems/system_add_test.dart' as system_add_test;
import 'systems/system_copy_test.dart' as system_copy_test;
import 'systems/system_create_test.dart' as system_create_test;
import 'systems/system_debounce_on_test.dart' as system_debounce_on_test;
import 'systems/system_dispose_test.dart' as system_dispose_test;
import 'systems/system_effects_test.dart' as system_effects_test;
import 'systems/system_event_interceptor_test.dart' as system_event_interceptor_test;
import 'systems/system_ignore_event_test.dart' as system_ignore_event_test;
import 'systems/system_log_test.dart' as system_log_test;
import 'systems/system_on_dispose_test.dart' as system_on_dispose_test;
import 'systems/system_on_run_test.dart' as system_on_run_test;
import 'systems/system_on_test.dart' as system_on_test;
import 'systems/system_react_latest_test.dart' as system_react_latest_test;
import 'systems/system_react_state_test.dart' as system_react_state_test;
import 'systems/system_react_test.dart' as system_react_test;
import 'systems/system_run_test.dart' as system_run_test;
import 'systems/system_run_with_context_test.dart' as system_run_with_context_test;
import 'systems/system_with_context_test.dart' as system_with_context_test;

void main() {
  effect_forwarder_test.main();
  system_add_test.main();
  system_copy_test.main();
  system_create_test.main();
  system_debounce_on_test.main();
  system_dispose_test.main();
  system_effects_test.main();
  system_event_interceptor_test.main();
  system_ignore_event_test.main();
  system_log_test.main();
  system_on_dispose_test.main();
  system_on_run_test.main();
  system_on_test.main();
  system_react_latest_test.main();
  system_react_state_test.main();
  system_react_test.main();
  system_run_test.main();
  system_run_with_context_test.main();
  system_with_context_test.main();
}
