name: love
description: A state management library that is declarative, predictable and elegant.
version: 0.1.2
homepage: https://github.com/LoveCommunity/love.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  typedef_equals: ^0.0.1

dev_dependencies:
  test: ^1.16.0